command:
  - uvicorn
  - main:app
  - --host=0.0.0.0
  - --port=8000

env:
  - name: DATABRICKS_HOST
    description: "Databricks workspace hostname (e.g., adb-xxx.azuredatabricks.net)"
  - name: DATABRICKS_HTTP_PATH
    description: "SQL warehouse HTTP path (e.g., /sql/1.0/warehouses/xxx)"
  - name: DATABRICKS_CATALOG
    description: "Unity Catalog catalog name"
  - name: DATABRICKS_CLIENT_ID
    description: "OAuth service principal client ID"
  - name: DATABRICKS_CLIENT_SECRET
    description: "OAuth service principal client secret"
