-- ============================================================================
-- Databricks Unity Catalog Delta Lake Tables for burnham_rng
-- ============================================================================
-- This file contains Delta table CREATE statements for the Databricks
-- burnham_rng catalog. Tables are organized into two schemas:
-- - project_intakes: Core project management and intake form data
-- - raw_documents: Document storage and management
--
-- Note: Delta Lake does not support traditional foreign key constraints or
-- PRIMARY KEY enforcement. All IDs are generated as UUIDs in the application
-- layer (Python uuid4). Foreign key relationships are enforced in app logic.
-- ============================================================================

-- Create schemas if they don't exist
CREATE SCHEMA IF NOT EXISTS burnham_rng.project_intakes;
CREATE SCHEMA IF NOT EXISTS burnham_rng.raw_documents;

-- ============================================================================
-- PROJECT_INTAKES SCHEMA TABLES
-- ============================================================================

CREATE TABLE IF NOT EXISTS burnham_rng.project_intakes.projects (
  id STRING NOT NULL,
  name STRING NOT NULL,
  description STRING,
  created_at TIMESTAMP NOT NULL
)
USING DELTA
COMMENT 'Top-level project containers. IDs are UUIDs generated by the application.';

CREATE TABLE IF NOT EXISTS burnham_rng.project_intakes.scenarios (
  id STRING NOT NULL,
  project_id STRING NOT NULL,
  name STRING NOT NULL,
  status STRING NOT NULL,
  preferred_model STRING,
  clarifying_questions STRING,
  clarifying_answers STRING,
  project_type STRING,
  project_type_confirmed BOOLEAN,
  created_at TIMESTAMP NOT NULL,
  confirmed_at TIMESTAMP
)
USING DELTA
COMMENT 'Individual evaluation scenarios. project_id references projects.id (app-enforced).';

CREATE TABLE IF NOT EXISTS burnham_rng.project_intakes.text_entries (
  id STRING NOT NULL,
  scenario_id STRING NOT NULL,
  content STRING NOT NULL,
  category STRING,
  created_at TIMESTAMP NOT NULL
)
USING DELTA
COMMENT 'Free-form text inputs categorized as feedstock, output_requirements, location, or constraints.';

CREATE TABLE IF NOT EXISTS burnham_rng.project_intakes.extracted_parameters (
  id STRING NOT NULL,
  scenario_id STRING NOT NULL,
  category STRING NOT NULL,
  name STRING NOT NULL,
  value STRING,
  unit STRING,
  source STRING NOT NULL,
  confidence STRING,
  is_confirmed BOOLEAN NOT NULL,
  created_at TIMESTAMP NOT NULL
)
USING DELTA
COMMENT 'AI-extracted parameters with confidence levels and source tracking.';

CREATE TABLE IF NOT EXISTS burnham_rng.project_intakes.upif_records (
  id STRING NOT NULL,
  scenario_id STRING NOT NULL,
  feedstock_type STRING,
  feedstock_volume STRING,
  feedstock_unit STRING,
  feedstock_parameters STRING,
  feedstock_specs STRING,
  feedstocks STRING,
  output_requirements STRING,
  output_specs STRING,
  location STRING,
  constraints STRING,
  confirmed_fields STRING,
  is_confirmed BOOLEAN NOT NULL,
  confirmed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
)
USING DELTA
COMMENT 'Consolidated UPIF with multi-feedstock support. JSON fields stored as STRING.';

CREATE TABLE IF NOT EXISTS burnham_rng.project_intakes.upif_chat_messages (
  id STRING NOT NULL,
  scenario_id STRING NOT NULL,
  role STRING NOT NULL,
  content STRING NOT NULL,
  applied_updates STRING,
  created_at TIMESTAMP NOT NULL
)
USING DELTA
COMMENT 'AI reviewer chat history with applied update tracking.';

CREATE TABLE IF NOT EXISTS burnham_rng.project_intakes.prompt_templates (
  id STRING NOT NULL,
  key STRING NOT NULL,
  name STRING NOT NULL,
  description STRING,
  template STRING NOT NULL,
  is_system_prompt BOOLEAN NOT NULL,
  updated_at TIMESTAMP NOT NULL
)
USING DELTA
COMMENT 'User-customizable AI prompt templates for extraction, clarification, review, and PDF summary.';

-- ============================================================================
-- RAW_DOCUMENTS SCHEMA TABLES
-- ============================================================================

CREATE TABLE IF NOT EXISTS burnham_rng.raw_documents.documents (
  id STRING NOT NULL,
  scenario_id STRING NOT NULL,
  filename STRING NOT NULL,
  original_name STRING NOT NULL,
  mime_type STRING NOT NULL,
  size STRING NOT NULL,
  extracted_text STRING,
  created_at TIMESTAMP NOT NULL
)
USING DELTA
COMMENT 'Uploaded file metadata and extracted text for AI processing.';

-- ============================================================================
-- OPTIMIZATION NOTES
-- ============================================================================
-- Delta Lake uses Z-order clustering instead of indexes. Run periodically:
-- OPTIMIZE burnham_rng.project_intakes.scenarios ZORDER BY (project_id);
-- OPTIMIZE burnham_rng.project_intakes.text_entries ZORDER BY (scenario_id);
-- OPTIMIZE burnham_rng.project_intakes.extracted_parameters ZORDER BY (scenario_id);
-- OPTIMIZE burnham_rng.project_intakes.upif_records ZORDER BY (scenario_id);
-- OPTIMIZE burnham_rng.project_intakes.upif_chat_messages ZORDER BY (scenario_id);
-- OPTIMIZE burnham_rng.raw_documents.documents ZORDER BY (scenario_id);
-- OPTIMIZE burnham_rng.project_intakes.prompt_templates ZORDER BY (key);
